services:
  - name: backend
    type: web
    env: python
    buildCommand: ""
    startCommand: gunicorn backend.wsgi --bind 0.0.0.0:8000
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:postgres@db:5432/postgres

  - name: frontend
    type: web
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://martech.onrender.com/api/
